name: CI BankManager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verification-du-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
    
      - name: Installation des d√©pendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        
      - name: Lancement des tests avec Pytest
        run: python -m pytest